### ISSUE TITLE
Header name case-insensitive 

### ISSUE THREAD

**Issue by MaGrMo** [gerdus/tus-dotnet-client#11]
Hello according to [rfc2616](https://www.ietf.org/rfc/rfc2616.txt),  Message Headers Field names are case-insensitive.
I faced with  problem that Envoy (CONTOUR) are transforms response headers to lower cases, and clients throws  exception "Offset Header Missing"   [code](https://github.com/gerdus/tus-dotnet-client/blob/51fdac77480a243a757106360513e667af6b87e5/TusClient/TusClient.cs#L323)

Thank you.

**Comment by gerdus** [comment]
Are you sure you are running the latest version? case-insensitive headers was added in pull request https://github.com/gerdus/tus-dotnet-client/pull/9

I have tested it with envoy proxy and seems to work fine. I have made a commit that adds example docker compose with envoy proxy and examples/tests.
