### ISSUE TITLE
Operation not permitted on HTTPS

### ISSUE THREAD

**Issue by j-hudecek** [gerdus/tus-dotnet-client#4]
I'm getting "Operation not supported on this platform" exception when calling Create on HTTPS connection (HTTP works fine).

**Comment by gerdus** [comment]
What server are you using?

**Comment by gerdus** [comment]
please provide a stacktrace of the exception

**Comment by j-hudecek** [comment]
in TusHTTPClient.PerformRequest:

    'request.ServicePoint' threw an exception of type 'System.PlatformNotSupportedException'
    at System.Net.SystemWebProxy.GetProxy(Uri destination)
    at System.Net.ServicePointManager.ProxyAddressIfNecessary(Uri& address, IWebProxy proxy)
    at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy)
    at System.Net.HttpWebRequest.get_ServicePoint()

send me a mail to j.hudecek@nki.nl and I can share the URL

**Comment by gerdus** [comment]
Ah it is giving an error on getting the system proxy. Makes more sense but why only for HTTPS is weird.
Seems rest sharp had the same problem: https://github.com/restsharp/RestSharp/issues/1061
Are you using  .Net Core 2.0?

**Comment by gerdus** [comment]
I have commited a fix for the issue.
Please test to see if it works for you.

**Comment by gerdus** [comment]
I have committed a fix for the issue.
Please test to see if it works for you.

**Comment by j-hudecek** [comment]
Yes, I'm on Core 2.0.
Yes catching the exception and throwing it away works as well. It would be nice to figure out the root cause, though. Thanks anyway!

**Comment by gerdus** [comment]
Thank you for reporting the issue.
Setting the proxy to null by default is actually the main fix, the try catch is just an abundance of caution.
Default system proxy in .net core is basically dummy object (https://github.com/dotnet/corefx/blob/master/src/System.Net.Requests/src/System/Net/SystemWebProxy.cs) that always throws and wasn't handled correctly by ServicePoint. See https://github.com/dotnet/corefx/pull/26925 for the unreleased fix in .net core.
Love that .net is open source now, makes tracking down these kinds of bugs possible.
