### ISSUE TITLE
Can this project be used in production environment now

### ISSUE THREAD

**Issue by bluetianx** [gerdus/tus-dotnet-client#6]
Can this project be used in production environment now？

**Comment by gerdus** [comment]
I am using it in production for my software ([smart-it.co.za](https://www.smart-it.co.za/)) and it has successfully uploaded over 200000 files of sizes varying between 1mb to 4gb from many client installations. We are using tus-node-server (node.js) server side.

If it is production quality for your use case is for you to decide and pull requests are welcome if you encounter issues.

**Comment by bluetianx** [comment]
ok  , thank you . I will use it in the furture
