### ISSUE TITLE
The Uploading is async or sync method?

### ISSUE THREAD

**Issue by jasonlee0927** [gerdus/tus-dotnet-client#7]
when i use this client in WPF to upload file, when the file uploading, the application window was frozen.
please help me to how to fix it.thanks！
` private void Client_Uploading(long bytesTransferred, long bytesTotal)
        {
            double alreadyTransferred = (double)bytesTransferred;
            double total = (double)bytesTotal;
            currentPercent = (int)((alreadyTransferred / total) * 100);
            txtStatus.Dispatcher.Invoke(() => txtStatus.Text = string.Format(" {0} %", currentPercent));
            progressBar.Dispatcher.Invoke(() => progressBar.Value = currentPercent);
        }`

**Comment by bluetianx** [comment]
It may be sync.

**Comment by gerdus** [comment]
uploading is sync. I am unfamiliar with WPF so I don't know but maybe just run the upload in a task/thread?
