### ISSUE TITLE
How to  upload a folder that contains many files

### ISSUE THREAD

**Issue by bluetianx** [gerdus/tus-dotnet-client#8]
How to  upload a folder that contains many files， I want to upload a folder  that contains many files

**Comment by tukao89** [comment]
I think you should upload a zip file, then extract when file is uploaded to server!

**Comment by gerdus** [comment]
I agree with @tudeptrai102 the zip file would be easiest way.

**Comment by bluetianx** [comment]
my code 

` static void Main(string[] args)
        {
            string ServerURL = "http://localhost:5000/files";
            var tc = new TusClient.TusClient();
            var mataDic = new Dictionary<string, string>();
            tc.Uploading += (bytesTransferred,  bytesTotal) => 
            {
                Console.WriteLine($" {bytesTransferred} / {bytesTotal }");
               Thread.Sleep(2000);
            };
            var fileInfo = new FileInfo("test.zip");
            var fileURL =tc.Create(ServerURL, fileInfo);
            tc.Upload(fileURL, fileInfo);
        }`

Problem：when I shut down the client that is  uploading  data ,then restart it ,the offset is 0,Not a value greater than 0. the client send data from 0. my test stie is [github](https://github.com/tusdotnet/tusdotnet/tree/master/Source/TestSites/AspNetCore_netcoreapp2.1_TestApp)

**Comment by gerdus** [comment]
Just rerunning that code won't resume an incomplete file.
According to the tus spec, to resume the file you need to use the same file URL. A new one is created because you always use tc.Create

**Comment by bluetianx** [comment]
my demo code 
`static void Main(string[] args)
        {
            string ServerURL = "http://localhost:5000/files";
            var tc = new TusClient.TusClient();
            var mataDic = new Dictionary<string, string>();
            int count = 0;
            tc.Uploading += (bytesTransferred,  bytesTotal) => 
            {
                count++;
                decimal perc = (decimal)(bytesTransferred / bytesTotal * 100.0);
                Console.WriteLine("Up {0} of {1}",  bytesTransferred, bytesTotal);
               Thread.Sleep(2000);
                if(count>5)
                tc.Cancel();
            };
            var fileInfo = new FileInfo("test.zip");
            var fileURL = "";
            fileURL = tc.Create(ServerURL, fileInfo);
            //fileURL = @"http://localhost:5000/files/6e4e6bb327444d5481b9608150f4fcc7";
            try
            {
                tc.Upload(fileURL, fileInfo);

            }
            catch(Exception ex)
            {

            }
            Console.WriteLine("Upload Resumed");

            var tc1 = new TusClient.TusClient();
            tc1.Uploading += (bytesTransferred, bytesTotal) =>
            {
                decimal perc = (decimal)(bytesTransferred / bytesTotal * 100.0);
                Console.WriteLine("Up {0} of {1}",  bytesTransferred, bytesTotal);
                Thread.Sleep(2000);
                //tc1.Cancel();
            };
            tc1.Upload(fileURL, fileInfo);

        }`
Problem: I have changed my code ,but it not work. it can not resume.

**Comment by bluetianx** [comment]
you cant run my test site [C# upload server](https://github.com/tusdotnet/tusdotnet/tree/master/Source/TestSites/AspNetCore_netcoreapp2.1_TestApp); 
you should comment some code as follows when you run the test site.
`private DefaultTusConfiguration CreateTusConfiguration(IServiceProvider serviceProvider)
        {
            var logger = serviceProvider.GetService<ILoggerFactory>().CreateLogger<Startup>();

            return new DefaultTusConfiguration
            {
                UrlPath = "/files",
                Store = new TusDiskStore(@"C:\tusfiles\"),
                Events = new Events
                {
                    OnBeforeCreateAsync = ctx =>
                    {
                        // Partial files are not complete so we do not need to validate
                        // the metadata in our example.
                        if (ctx.FileConcatenation is FileConcatPartial)
                        {
                            return Task.CompletedTask;
                        }

                       /* if (!ctx.Metadata.ContainsKey("name"))
                        {
                            ctx.FailRequest("name metadata must be specified. ");
                        }

                        if (!ctx.Metadata.ContainsKey("contentType"))
                        {
                            ctx.FailRequest("contentType metadata must be specified. ");
                        }*/

                        return Task.CompletedTask;
                    },
                    OnCreateCompleteAsync = ctx =>
                    {
                        logger.LogInformation($"Created file {ctx.FileId} using {ctx.Store.GetType().FullName}");
                        return Task.CompletedTask;
                    },
                    OnBeforeDeleteAsync = ctx =>
                    {
                        // Can the file be deleted? If not call ctx.FailRequest(<message>);
                        return Task.CompletedTask;
                    },
                    OnDeleteCompleteAsync = ctx =>
                    {
                        logger.LogInformation($"Deleted file {ctx.FileId} using {ctx.Store.GetType().FullName}");
                        return Task.CompletedTask;
                    },
                    OnFileCompleteAsync = ctx =>
                    {
                        logger.LogInformation($"Upload of {ctx.FileId} completed using {ctx.Store.GetType().FullName}");
                        // If the store implements ITusReadableStore one could access the completed file here.
                        // The default TusDiskStore implements this interface:
                        //var file = await ((tusdotnet.Interfaces.ITusReadableStore)ctx.Store).GetFileAsync(ctx.FileId, ctx.CancellationToken);
                        return Task.CompletedTask;
                    }
                },
                // Set an expiration time where incomplete files can no longer be updated.
                // This value can either be absolute or sliding.
                // Absolute expiration will be saved per file on create
                // Sliding expiration will be saved per file on create and updated on each patch/update.
                Expiration = null
            };
        }`

**Comment by gerdus** [comment]
How large is your test.zip file? Currently the upload piece size is 3MB so if it is less than that it would start from 0 because no segment/piece uploaded completely.

**Comment by bluetianx** [comment]
yep  it is bigger than 3M，you can test my demo

**Comment by bluetianx** [comment]
I test  nodeJs server site today .It do not work.

**Comment by bluetianx** [comment]
PS .demo code as follows 
`const tus = require('tus-node-server');
const express = require('express');
const server = new tus.Server();
server.datastore = new tus.FileStore({
    path: '/files'
});

const app = express();
const uploadApp = express();
uploadApp.all('*', server.handle.bind(server));
app.use('/uploads', uploadApp);

const host = '127.0.0.1';
const port = 1080;
app.listen(port, host);`

**Comment by gerdus** [comment]
Problem is in your code that interrupts the upload the first time. Upload progress is in 4096 byte increments and you are stopping after 5 iterations thus 20Kb and so nowhere near the default 3Mb upload chunk size.

suggested replacement code:
` int ChunkSize = (int)Math.Ceiling(3 * 1024.0 * 1024.0); //3 mb

tc.Uploading += (bytesTransferred, bytesTotal) =>
{
    decimal perc = (decimal)(bytesTransferred / bytesTotal * 100.0);
    Console.WriteLine("Up {0} of {1}", bytesTransferred, bytesTotal);
    Thread.Sleep(10);
    if (bytesTransferred > (ChunkSize+1))
    {
        tc.Cancel();
    }
                
}; `

**Comment by bluetianx** [comment]
holy ， It is working... thank you very much

**Comment by gerdus** [comment]
Glad to hear 👍
